on:
  push:
    branches:
      - main
  pull_request:
  release:
    types:
      - released

name: Build

permissions:
  checks: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
          - "1.75.0"

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
      - uses: Swatinem/rust-cache@v2.7.3
      - run: cargo build --release --all-targets --all-features
      - run: cargo test --release --all-features

  minimal-versions:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - uses: Swatinem/rust-cache@v2.7.3
      - run: cargo update -Z direct-minimal-versions
      - run: cargo build --release --all-targets --all-features

  clippy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v2.7.3
      - run: cargo clippy --all-targets --all-features

  fmt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - run: cargo fmt --all -- --check

  publish:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    needs:
      - test
      - minimal-versions
      - clippy
      - fmt

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
